In [1]:
from google.colab import files
uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User has uploaded the file {fn} with length {len(uploaded[fn])} bytes')

Saving iris.data to iris.data
User has uploaded the file iris.data with length 4551 bytes


In [26]:
#Read the data after uploading it
import pandas as pd
import io
data = pd.read_csv(io.StringIO(uploaded['iris.data'].decode('utf-8')),header=None)
data.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [27]:
#importing important libraries
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

In [28]:
#Dividing data into X and y
X = data.iloc[:,:4].values
y = data.iloc[:,4].values

In [29]:
#Use the labelencoder
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y1 = encoder.fit_transform(y)
Y = pd.get_dummies(y1).values

In [30]:
# Do the train-test split
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test = train_test_split(X,Y, test_size=0.3, random_state=0)

In [31]:
# Now create the model of the ANN
model = Sequential()
model.add(Dense(units=4,input_shape=(4,),activation='relu')) #Taking input of 4 and hidden layer of 4 neuron
model.add(Dense(3,activation='softmax'))  # Output into one of the 3

In [32]:
#Let's compile the model
model.compile(optimizer='Adam', loss='categorical_crossentropy',metrics=['accuracy'])

In [33]:
model.fit(X_train,y_train, batch_size=10,epochs=100)

Epoch 1/100
11/11 [==============================] - 1s 3ms/step - loss: 2.6530 - accuracy: 0.3714
Epoch 2/100
11/11 [==============================] - 0s 2ms/step - loss: 2.3810 - accuracy: 0.3714
Epoch 3/100
11/11 [==============================] - 0s 2ms/step - loss: 2.1579 - accuracy: 0.3714
Epoch 4/100
11/11 [==============================] - 0s 2ms/step - loss: 1.9666 - accuracy: 0.3714
Epoch 5/100
11/11 [==============================] - 0s 3ms/step - loss: 1.8144 - accuracy: 0.3714
Epoch 6/100
11/11 [==============================] - 0s 3ms/step - loss: 1.6940 - accuracy: 0.4190
Epoch 7/100
11/11 [==============================] - 0s 3ms/step - loss: 1.5802 - accuracy: 0.6381
Epoch 8/100
11/11 [==============================] - 0s 2ms/step - loss: 1.4843 - accuracy: 0.6857
Epoch 9/100
11/11 [==============================] - 0s 3ms/step - loss: 1.3838 - accuracy: 0.6952
Epoch 10/100
11/11 [==============================] - 0s 2ms/step - loss: 1.3032 - accuracy: 0.6952
Epoch 11/

In [36]:
import numpy as np
y_pred = model.predict(X_test)
y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred, axis=1)

2/2 [==============================] - 0s 5ms/step


In [37]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class, y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.50      0.67        18
           2       0.55      1.00      0.71        11

    accuracy                           0.80        45
   macro avg       0.85      0.83      0.79        45
weighted avg       0.89      0.80      0.80        45

[[16  0  0]
 [ 0  9  9]
 [ 0  0 11]]


In [38]:
#Accuracy on test set
(16+9+11)/(16+9+9+11)

0.8